services:
  - type: web
    name: dse-backend-api
    env: node
    plan: free
    buildCommand: npm install --include=optional
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: TZ
        value: Asia/Dhaka
      - key: PORT
        value: 5001

  - type: static
    name: dse-frontend
    plan: free
    buildCommand: npm install --include=optional && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: VITE_API_URL
        value: https://dse-xvn2.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
